### ISSUE TITLE
Small bug in PlaceOrder

### ISSUE THREAD

**Issue by robotajet** [microwavedcola1/mango-v3-service#10]
This data type should be a `float` instead of `int` https://github.com/microwavedcola1/mango-v3-service/blob/70b3c3f20253f35b7cdf4051b60cbf0b15ae95cf/py/mango_service_v3_py/dtos.py#L124

```python
class PlaceOrder(CamelCaseModel):
    market: str
    side: Side
    price: int
    type: str
    size: float
    reduce_only: bool
    ioc: bool
    post_only: bool
    client_id: int

```

Having  it as an `int` will truncate your price and may cause you to trade at prices you didn't want.

**Comment by microwavedcola1** [comment]
thanks, I fixed it, btw the repo is now maintained under the org,
